### ISSUE TITLE
Posts from non followed user

### ISSUE THREAD

**Issue by Bugs1415** [pjchavarria/Aozora#100]
![image](https://cloud.githubusercontent.com/assets/18428667/14477938/c1db9200-00e7-11e6-840f-7d0d175291fc.png)
![image](https://cloud.githubusercontent.com/assets/18428667/14477939/c235716c-00e7-11e6-9442-e9282cd8e004.png)

**Comment by pjchavarria** [comment]
Fixed on 5.7.4 / 132
