### ISSUE TITLE
Thread tag bug

### ISSUE THREAD

**Issue by casillaskhoren1** [pjchavarria/Aozora#114]
Some threads are showing under the wrong tag section.
This might be because some threads were assigned with more than one tag on older versions of the app, so even though it shows only one tag under the thread on the latest beta, the thread itself is still assigned to more than one tag.
As you can see in the image below, it's showing some threads with Manga, Fan Club and even Sword Art Online (anime titles) tag under the Off-Topic tag section.
![image](https://cloud.githubusercontent.com/assets/6556281/14767129/ef1d746e-0a1e-11e6-822d-0583cf18038b.jpg)

**Comment by casillaskhoren1** [comment]
It seems that tapping on edit thread option then just resending the post fixes this issue, so if there's a way to automatically refresh the threads (resend them) on the new beta, then the issue will be solved completely.

**Comment by pjchavarria** [comment]
The problem is, now threads only show one tag but the old tags are still in db, so this will be solved eventually when new update is released, the manual option is to update a thread and set one tag (which will override others)
