### ISSUE TITLE
Anime identity crisis bug

### ISSUE THREAD

**Issue by NekoAttack** [pjchavarria/Aozora#116]
In "view library": 
• Anime is watchlist opens anime in planning
• Anime in planning opens anime completed
• Anime in completed opens anime on hold
• However when you click on an anime that is on hold it crashes. Crashes also occured when opening an anime that was completed.

**Comment by casillaskhoren1** [comment]
Note that it happens only when viewing library through the "View Library" feature.

**Comment by pjchavarria** [comment]
fixed on #105, thank you!
