### ISSUE TITLE
Comment count on posts 

### ISSUE THREAD

**Issue by Zephyyr** [pjchavarria/Aozora#117]
![image](https://cloud.githubusercontent.com/assets/17292702/14771128/e4c2bb58-0a57-11e6-911e-62e739f95203.png)
![image](https://cloud.githubusercontent.com/assets/17292702/14771129/e5331d6c-0a57-11e6-8f91-464c7dd692f8.png)

It shows 7 comments before entering the thread. But once inside it shows only 2. It happens in all posts.

**Comment by pjchavarria** [comment]
that feature is not finished, please read release notes in testflight before reporting bugs.
