### ISSUE TITLE
Unable to Delete Timeline Posts When Notif Redirected

### ISSUE THREAD

**Issue by rwdj** [pjchavarria/Aozora#119]
Click "xxxxx commented on a post in your profile"
// >
Hold to delete
// >
Nothing....

**Comment by rwdj** [comment]
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/17169963/14772486/dd91c986-0a6c-11e6-90dd-ac8c9de70b13.png)

**Comment by pjchavarria** [comment]
hmm it's not hold, it's tap to edit, is this still happening on last build?

**Comment by pjchavarria** [comment]
seems to be working now
