### ISSUE TITLE
Gif bug

### ISSUE THREAD

**Issue by casillaskhoren1** [pjchavarria/Aozora#122]
When you tap on a gif to view it/save etc. the gif stops at the frame that it was showing when you tapped on it. Basically, it freezes when you tap on a gif.

**Comment by pjchavarria** [comment]
Not a bug, since we're using a new way of displaying gifs the lightbox library don't support them out of the box, will need to use something else.

**Comment by pjchavarria** [comment]
this was fixed on #105
