### ISSUE TITLE
Skip signup crash

### ISSUE THREAD

**Issue by casillaskhoren1** [pjchavarria/Aozora#124]
Tapping on "Skip Signup" in both Aozora beta (140) and Anime Trakr App Store version is crashing the app.

**Comment by sgript** [comment]
Is this still an issue? As I've just tried this on an iPhone 6, seems to work fine. Can you check on other devices also?

**Comment by casillaskhoren1** [comment]
I tried all to reproduce the crash in many ways and it seams that the crash happens when you have at least signed in once then signed out. It's happening on iPhone 5s and iPad 4th Gen.

**Comment by pjchavarria** [comment]
found the issue, happens when last viewed tab is profile, thanks for the report @casillaskhoren1

**Comment by pjchavarria** [comment]
fixed on #105
