### ISSUE TITLE
Wrong Episode Count on Series

### ISSUE THREAD

**Issue by enanogrande** [pjchavarria/Aozora#129]
Some of the currently running series in the app have wrong episode counts, as in they count unreleased episodes as released. Therefore, even after having watched all the currently released episodes, the app will say "1 behind". Current series with this problem are:

Dragon Ball Super
Sakamoto Desu Ga

This seems to happen whenever a series skips a week in it broadcast, and for some reason the Aozora database doesn't take account of the skipped week. Whats notable is that other series have skipped weeks and Aozora has acted accordingly, so it's odd that these two (and one as high profile as DBS) didn't get updated.

**Comment by sgript** [comment]
There's really nothing we can do _directly_ to solve this, report this to https://github.com/joshstar/AniList-API-Docs/issues

Closed.
