### ISSUE TITLE
Comment graphical bug

### ISSUE THREAD

**Issue by jamesgorm** [pjchavarria/Aozora#130]
This only seems to happen when opening the app from the lock screen via a reply. The comment button is multiplied and it does not let you view any previous comments other than the ones on the screen. 

![image](https://cloud.githubusercontent.com/assets/17103270/15002736/8f4ba726-1172-11e6-9782-4e2a6e2e1d60.png)

**Comment by pjchavarria** [comment]
fixed on #105
