### ISSUE TITLE
Comments in beta 146

### ISSUE THREAD

**Issue by Knight070** [pjchavarria/Aozora#132]
Comments disappeared under several posts in the profile, however they are still there in the stable app and in the post count.. Only couldn't view them in the beta

**Comment by pjchavarria** [comment]
Can you reproduce that? What were the steps you took?

**Comment by Knight070** [comment]
Didn't do anything but since i downloaded the beta some comments couldn't be view however it's still there.. It's like the threads when they show 0 comments

**Comment by pjchavarria** [comment]
will be working fine when the app is updated
