### ISSUE TITLE
Black space bug

### ISSUE THREAD

**Issue by casillaskhoren1** [pjchavarria/Aozora#137]
This happens only when you don't have Pro/Pro+ unlocked!!
When you first sign in to the app (or if you have signed in already, sign out then sign in again), you'll notice a black space in the Notifications/Announcement tab.
It can also be reproduced by going back and forth to the Notifications/Announcement tab.
![image](https://cloud.githubusercontent.com/assets/6556281/15096821/072e37ec-1509-11e6-98b3-c91adae1acc8.png)

**Comment by pjchavarria** [comment]
fixed on #105
