### ISSUE TITLE
Crash on expanded gifs on iPad

### ISSUE THREAD

**Issue by TheNaughtyOne** [pjchavarria/Aozora#144]
I've been able to reproduce this many times. Touch an image to expand it, then press the contextual button that appears in the upper right hand corner (square button with a vertical arrow out the top) and Aozora will stall and crash.

**Comment by P5YCH0DE** [comment]
That's the problem with any kind of sharing, in the app with iPad. I think it might be a layout problem, but idk.

**Comment by P5YCH0DE** [comment]
I already posted a issue with this crashing but not for the GIFS.

**Comment by pjchavarria** [comment]
fixed on #105
