### ISSUE TITLE
App crashing on both Aozora/Anime Trakr

### ISSUE THREAD

**Issue by NekoAttack** [pjchavarria/Aozora#34]
In the home section at the top there are photos of airing anime. sliding them rapidly until the end, and continuing even after the last picture makes the app crash. 
[https://files.slack.com/files-pri/T0CFXR7TJ-F0LKQ5X8X/slack_for_ios_upload.mp4](url)
Video by Shinobu

**Comment by pjchavarria** [comment]
Thanks, fixed
