### ISSUE TITLE
App crashed when I open very quicikly "All seasons"

### ISSUE THREAD

**Issue by nickwlker** [pjchavarria/Aozora#39]
If I open the app and very quickly tap on seasons and choose all seasons - app crashed. It repeats after restart the app.

**Comment by pjchavarria** [comment]
Wasn't able to reproduce, any other idea?

**Comment by nickwlker** [comment]
@pjchavarria I can not reproduce it now, because you changed the way how looks seasons. Previously, I just had a list of seasons without thumbs, so I think it disappear for now.
