### ISSUE TITLE
Keep getting logged out

### ISSUE THREAD

**Issue by John3gbert** [pjchavarria/Aozora#40]
![image](https://cloud.githubusercontent.com/assets/17130733/12922139/117d80b2-cf05-11e5-8b38-8f23c9d9cc50.png) 
I close the app for a little and when I come back I have to sign in again.

**Comment by thetenguwolf** [comment]
Hi, I'm doing the beta test for Anime trakr, and I'm having problems with the app closing immediately after I open it. Like I had with Aozora.

**Comment by pjchavarria** [comment]
hey @John3gbert wasn't able to reproduce, is this still happening?

**Comment by thetenguwolf** [comment]
Yes, sadly it's still happening. Animetrakr always worked brilliantly until
I switched over to the beta.

Originally when the Aozora app launched it would instantly close like this
for me all the time. So I just stuck with using Animetrakr, but now neither
app works.

**Comment by pjchavarria** [comment]
What's your username and did you logged in with fb or email?

**Comment by pjchavarria** [comment]
closing due to innactivity, feel free to re-open
