### ISSUE TITLE
Profile page on the side and almost invisible, on iPad.

### ISSUE THREAD

**Issue by bigbenr** [pjchavarria/Aozora#42]
![image](https://cloud.githubusercontent.com/assets/17155358/12939461/2519df42-cfc0-11e5-895f-7ddb6e392093.png)
![image](https://cloud.githubusercontent.com/assets/17155358/12939462/253fa966-cfc0-11e5-800d-9b55b550b4be.png)
It got worse after I had to relog in.

**Comment by pjchavarria** [comment]
This has been fixed on last build
