### ISSUE TITLE
New reply button bug 

### ISSUE THREAD

**Issue by iShinobu** [pjchavarria/Aozora#44]
I think it's because of the Ad 

https://files.slack.com/files-pri/T0CFXR7TJ-F0LS0JM4J/slack_for_ios_upload.mp4

**Comment by pjchavarria** [comment]
video is dead

**Comment by iShinobu** [comment]
https://www.dropbox.com/s/h7jsyvqv381ieen/reply%20button.mp4?dl=0

**Comment by pjchavarria** [comment]
This seems to be fixed, feel free to re-open
