### ISSUE TITLE
Anime Trakr widget not reporting episodes to watch

### ISSUE THREAD

**Issue by NekoAttack** [pjchavarria/Aozora#45]
![image](https://cloud.githubusercontent.com/assets/17128919/12958220/7c23c594-cfe5-11e5-9d6b-c66e7c7950a6.png)

The aozora one is working fine, but the anime trakr one is not. Says no episodes to watch, but since aozora and anime trakr are now the same it should report the same episodes. Also the message gets cut

**Comment by pjchavarria** [comment]
You need to open the app for this to work, reopen if needed.
