### ISSUE TITLE
When switching the first tab, the banner is stuck on two anime.

### ISSUE THREAD

**Issue by bigbenr** [pjchavarria/Aozora#48]
Not systematic. Could be when switching tabs several times and rapidly.
![image](https://cloud.githubusercontent.com/assets/17155358/12959689/d8d6569c-d037-11e5-818c-61d32d24f9a1.png)

**Comment by Masheri** [comment]
This also hoppens when turning the screen on an iPad 
![image](https://cloud.githubusercontent.com/assets/17168771/12963944/b470ddac-d04d-11e5-81a0-e10048de4d6c.png)
