### ISSUE TITLE
Refresh button either not working or not refreshing images

### ISSUE THREAD

**Issue by rwdj** [pjchavarria/Aozora#51]

**Comment by rwdj** [comment]
Refresh "pull"?

**Comment by rwdj** [comment]
http://tinypic.com/r/2qjghvc/9

**Comment by pjchavarria** [comment]
Can't see the image, you can drag and drop it here

**Comment by rwdj** [comment]
![2qjghvc](https://cloud.githubusercontent.com/assets/17169963/12997350/6024a472-d106-11e5-8950-4c22c2ce83a7.jpg)

**Comment by rwdj** [comment]
This image was preceded by several of the same action, so it shows the problem (image not loaded), the action (refreshing), and the issue (image not loading after refreshing). Whether the images alone are the extent of this, i have been unable to find time to test it further.

**Comment by pjchavarria** [comment]
seems fixed, feel free to re-open
