### ISSUE TITLE
Status bar disappear

### ISSUE THREAD

**Issue by iShinobu** [pjchavarria/Aozora#53]
Status bar disappears when clicking the Ad.

Video : 
https://files.slack.com/files-pri/T0CFXR7TJ-F0LU72F6H/slack_for_ios_upload.mp4

**Comment by pjchavarria** [comment]
Ugh Slack deleted it, can you send me the steps to reproduce?
![image](https://cloud.githubusercontent.com/assets/1723531/12997255/1fdbc36a-d0ec-11e5-837c-c2fcaa2c996d.png)

**Comment by iShinobu** [comment]
https://www.dropbox.com/s/8z5ua7h05jykqiq/status.mp4?dl=0

**Comment by pjchavarria** [comment]
it seems fixed now, feel free to re-open
