### ISSUE TITLE
Aozora keeps on asking me my iTunes account password, each time I open the app.

### ISSUE THREAD

**Issue by bigbenr** [pjchavarria/Aozora#63]
Even after restarting my iDevice. Build 112.

**Comment by sgript** [comment]
I think this is an iOS issue. I get it often too, pretty much everywhere

**Comment by Zak-Adelman** [comment]
I have run into this bug with other apps as well.  The best solutions we could come up with was 
1: reinstall the app (rarely works but has)
2: Go to your settings app, log out of iCloud, reboot, and log back in.
3: do a backup, reinstall iOS, and restore from the backup

The success rate is usually in that order.

**Comment by pjchavarria** [comment]
This is probably an apple bug, feel free to re-open if still happens
