### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by casillaskhoren1** [pjchavarria/Aozora#67]
When you try to open any section on the Home tab before it completely loads, the app will crash.

For e.g. try to tap on "Discover >" before it shows anime covers and the app will crash. Wait for it to load then tap on it and it'll open just fine. But if you try to open for e.g. "Top Anime" before it loads, again the app will crash.

**Comment by Zephyyr** [comment]
Yeah, crashes for me too.

**Comment by pjchavarria** [comment]
This only happens on calendar though
