### ISSUE TITLE
MAL Login "Wrong Credentials"  -Anime Trakr

### ISSUE THREAD

**Issue by CyberSub-Zero00** [pjchavarria/Aozora#71]
I have installed both Aozora and Anime Trakr, now those two apps are practically the same (like the Scion FRS and the Subaru BRZ Lol) but for some reason I can login into Mal with no issues on Aozora but on Anime Trakr I get the message that my credentials are wrong.

**Comment by sgript** [comment]
This was fixed by @pjchavarria
