### ISSUE TITLE
Showing the comment several times

### ISSUE THREAD

**Issue by rahadasdy** [pjchavarria/Aozora#87]
When you get a notification that someone commented on your post, when you open it, you see the same cmmt and the same time several times like tge picture shows!!
![image](https://cloud.githubusercontent.com/assets/17207480/13287136/1f8238c8-db0e-11e5-95ae-04bce4817a6e.png)

**Comment by pjchavarria** [comment]
seems fixed, feel free to re-open if still happening to you
