### ISSUE TITLE
Multiple Posts

### ISSUE THREAD

**Issue by Bugs1415** [pjchavarria/Aozora#97]
When making a posts it gets stucked on "sending" then goes back to "send" when pressed more than once creates multiple posts (the text box doesn't pop off  # @automatically)`
![image](https://cloud.githubusercontent.com/assets/18428667/14474295/a8176bb0-00d2-11e6-807b-fdc46626ccaf.png)
![image](https://cloud.githubusercontent.com/assets/18428667/14474296/a84ea170-00d2-11e6-8c71-1110c8892cd4.png)
![image](https://cloud.githubusercontent.com/assets/18428667/14474297/a851ddc2-00d2-11e6-9964-22c08c376752.png)

**Comment by pjchavarria** [comment]
Fixed on 5.7.4 / 132
